aws_config:
  aws.secret.access.key: ifbxHc+6LSTOpAG4v9IiCGmQ1Um8BCJslMvupJhm
  aws.access.key.id: AKIAJAMZK2VGKQIOQ3VQ
  bucket: pipecandy-ohio
  sqs.region: us-east-2
  s3.region: us-east-2


postgres-config:
  # ohio rds
  user: postgres
  password: postgrespassword
  db_ip: market-poc-alpha-1.ctay8oofrwrd.ap-south-1.rds.amazonaws.com
  port: 5432
  database: postgres
  twitter.feed.table: data_stream.twitter_feeds
  news.feed.table: data_stream.news_feeds
  twitter.metadata.table: data_stream.twitter_metadata
  comany_list_table: data_stream.handles_to_track

twitter-config:
  tweet_data_dir: /home/ubuntu/twitter_pdfs

email-config:
  username: mechkcoders@gmail.com
  password: password@gmail

alphavantage-config:
  upcoming.results.table: share_market_data.upcoming_results
  share.price.table: share_market_data.alphavantage_data_points
