aws_config:
  aws.secret.access.key: ifbxHc+6LSTOpAG4v9IiCGmQ1Um8BCJslMvupJhm
  aws.access.key.id: AKIAJAMZK2VGKQIOQ3VQ
  bucket: pipecandy-ohio
  sqs.region: us-east-2
  s3.region: us-east-2


postgres-config:
  # ohio rds
  user: postgres
  password: postgrespassword
#  db_ip: market-poc-alpha-1.ctay8oofrwrd.ap-south-1.rds.amazonaws.com
  db_ip: market-poc-alpha-2.cc9kvgcpuesr.ap-south-1.rds.amazonaws.com
  port: 5432
  database: postgres
  twitter.feed.table: data_stream.twitter_feeds
  comany_list_table: data_stream.handles_to_track

twitter-config:
  tweet_data_dir: /home/ubuntu/twitter_pdfs

email-config:
  username: mechkcoders@gmail.com
  password: password@gmail

alphavantage-config:
  upcoming.results.table: share_market_data.upcoming_results
  share.price.table: share_market_data.alphavantage_data_points

bse_config:
  upcoming_result_table: bse.result_dates
  filtered_stock_list_table: bse.filtered_stock_info
  announcements_table: bse.bse_announcements
  market_stat_table: bse.stock_stats


bse_send_result_notification:
  checkpointing_table: bse.processed_bse_news
  upcoming_result_table: bse.result_dates
  historical_result_time_info_file: text_files/historical_bse_result_times.csv

kite_config:
  instrument_mapping_table: kite.instrument_tokens
  session_info_table: kite.authentication_details

alert_config:
  mode: cloudwatch

exit_config:
  strategy: trailing_stoploss
#  strategy: absolute
  loss_margin_limit_percent: 1.5
  profit_margin_limit_percent: 2.5
  stop_loss_update_threshold_percent: 1.5
  stop_loss_threshold_percent: 1.5





